# Declare variables to be passed into your templates.
name: urxiv-browse
namespace: default
port: 80

scaling:
  replicas: "1"

env:
  aws:
    key: 'asd123'
  db:
    endpoint: "mysql://localhost:5432"
  s3:
    host: "urxiv.s3.amazonaws.com"
    bucket_name: "urxiv"
    service: "urxiv"
    port: 80

image:
  name: "ivanantonov97/urxiv_browse"
  tag: "0.0.6"

loglevel: "40"

labels:
  subsystem: frontend
ingress:
  host: ivan-antonov.art
  path: /*
  name: urxiv-browse-ingress
  auth_url: /auth
