# Declare variables to be passed into your templates.
name: urxiv-submission
namespace: default

scaling:
  replicas: "1"

config:
  loglevel: "40"
  wait_for_services: 1
  wait_on_startup: 10

labels:
  subsystem: submission
ingress:
  proto: https
  host: ivan-antonov.art
  name: urxiv-submission-ingress
  path: /
  auth_url: "http://ivan-antonov.art/auth"

env:
  # email:
  #   hostname:
  #     port:
  #       username:
  #         password:
  #           ssl:
  aws:
    key: 'asd123'
    key_id: 'nope'
    key_secret: 'nope'
    region: 'us-west-2'

  jwt:
    secret: "foosecret"

  vault:
    enabled: "0"
    host: "localhost"
    port: 3001
    role: "urxiv-submission"

  s3:
    host: "urxiv.s3.amazonaws.com"
    bucket_name: "urxiv"
    service: "urxiv"
    port: 80

  db:
    endpoint: "mysql://localhost:5432"
    track_mod: false
  redis:
    host: "localhost"
    port: 7000
    db: "0"
  kinesis:
    stream: "submissionEvents"
    shard_id: "0"
    endpoint: "localhost"
    type: "trim-horizon"
    verify: "0"


submission_agent:
  port: 81
  image:
    name: "ivanantonov97/urxiv_submission_agent"
    tag: "0.0.1"
  env:
    agent_prefix: "submission-agent-"
    worker_prefix: "submission-worker"

submission_preview:
  path: "/preview"
  port: 81
  linking_to:
    host: "urxiv"
    port: 81
  image:
    name: "ivanantonov97/urxiv_submission_preview"
    tag: "0.0.1"

submission_ui:
  path: /submit
  port: 82
  image:
    name: "ivanantonov97/urxiv_submission_ui"
    tag: "0.0.1"

submission_filemanager:
  path: /upload
  port: 83
  image:
    name: "ivanantonov97/urxiv_submission_filemanager"
    tag: "0.0.1"

submission_metadata:
  path: /submission
  port: 84
  image:
    name: "ivanantonov97/urxiv_submission_metadata"
    tag: "0.0.1"

# submission_compiler:
#   path: /

# submission_classifier:
#   path: /

# submission_plaintext:
#   path: /
