# Declare variables to be passed into your templates.
name: urxiv-auth
namespace: default

scaling:
  replicas: "1"

labels:
  subsystem: auth
ingress:
  host: ivan-antonov.art
  name: urxiv-auth-ingress

env:
  aws:
    key: 'asd123'
    key_id: 'nope'
    key_secret: 'nope'
    region: 'us-west-2'

  redis:
    host: "localhost"
    port: 7000
    database: "0"

  jwt:
    secret: "foosecret"

  captcha:
    secret: "foobar"

  db:
    endpoint: "mysql://localhost:5432"

  vault:
    enabled: "0"
    host: "localhost"
    port: 3001
    role: "urxiv-submission"

  s3:
    host: "urxiv.s3.amazonaws.com"
    bucket_name: "urxiv"
    service: "urxiv"
    port: 80

accounts:
  path: /accounts
  port: 81
  image:
    name: "ivanantonov97/urxiv_auth_accounts"
    tag: "0.0.2"

registry:
  paths:
    user: /user
    register: /register
    lost_password: /lost_password
  port: 82
  image:
    name: "ivanantonov97/urxiv_auth_registry"
    tag: "0.0.1"

authenticator:
  path: /auth
  port: 83
  image:
    name: "ivanantonov97/urxiv_auth_authenticator"
    tag: "0.0.1"

loglevel: "40"
