apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: urxiv-browse-ingress
    service-group: api
    env: "{{ .Values.namespace }}"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
        - pathType: ImplementationSpecific
          path: "{{ default "/*" .Values.ingress.path }}"
          backend:
            service:
              name: "{{ .Values.name }}"
              port:
                number: {{ .Values.port }}
