apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ .Values.name }}"
    service-group: api
    log-style: uwsgi
    env: "{{ .Values.namespace }}"
spec:
  replicas: {{  int .Values.scaling.replicas }}
  selector:
    matchLabels:
      subsystem: "{{ .Values.labels.subsystem }}"
  template:
    metadata:
      labels:
        subsystem: "{{ .Values.labels.subsystem }}"
        container: "{{ .Values.name }}"
        service-group: api
        log-style: uwsgi
        env: "{{ .Values.namespace }}"
    spec:
      serviceAccount: urxiv-submission
      containers:
        - name: "{{ .Values.name }}:submission_ui"
          image: "{{ .Values.submission_agent.image.name }}:{{ .Values.accounts.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: VAULT_ENABLED
              value: "0"
            - name: KINESIS_STREAM
              value: "{{ .Values.kinesis.stream }}"
            - name: KINESIS_SHARD_ID
              value: "{{ .Values.kinesis.shard_id }}"
            - name: FILEMANAGER_PATH
              value: "{{ .Values.filemanager.path }}"
            - name: VAULT_ENABLED
              value: "{{ .Values.env.vault.enabled }}"
            - name: APPLICATION_ROOT
              value: "{{ .Values.ingress.path }}"
            - name: BASE_SERVER
              value: "{{ .Values.ingress.host }}"
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
        - name: "{{ .Values.name }}:submission_filemanager"
          image: "{{ .Values.submission_ui.image.name }}:{{ .Values.registry.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          resources:
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
        - name: "{{ .Values.name }}:submission_agent"
          image: "{{ .Values.authenticator.image.name }}:{{ .Values.submission_filemanager.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
            limits:
              cpu: 300m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
