kind: Service
apiVersion: v1
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ .Values.name }}"
    service-group: api
    log-style: uwsgi
    env: "{{ .Values.namespace }}"

spec:
  type: NodePort
  ports:
    - port: {{ .Values.submission_agent.port }}
      targetPort: 8081
      protocol: TCP
      name: http
    - port: {{ .Values.submission_ui.port }}
      targetPort: 8082
      protocol: TCP
      name: http
    - port: {{ .Values.submission_filemanager.port }}
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ .Values.name }}"
