apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: urxiv-browse-ingress
    service-group: api
    env: "{{ .Values.namespace }}"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "{{ .Values.ingress.auth_url }}"
    # Look at issue https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#configuration-snippet
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   proxy_set_header Authorization $upstream_http_authorization;
    #   proxy_set_header X-Request-ID $request_id;
    nginx.ingress.kubernetes.io/rewrite-target: "/*"
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "false" Don't add
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/server-snippet: |
    #     if ($http_x_forwarded_proto = 'http') {
    #       return 301 https://$host$request_uri;
    #     }
spec:
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
        - pathType: Exact
          path: "{{ .Values.submission_ui.path }}"
          backend:
            service:
              name: "{{ .Values.name }}"
              port:
                number: {{ .Values.submission_ui.port }}
        - pathType: Exact
          path: "{{ .Values.submission_filemanager.path }}"
          backend:
            service:
              name: "{{ .Values.name }}"
              port:
                number: {{ .Values.submission_filemanager.port }}
  - host: "{{ cat "www." .Values.ingress.host | replace " " "" }}"
    http:
      paths:
        - pathType: Exact
          path: "{{ .Values.submmision_ui.path }}"
          backend:
            service:
              name: "{{ .Values.name }}"
              port:
                number: {{ .Values.submission_ui.port }}
        - pathType: Exact
          path: "{{ .Values.submission_filemanager.path }}"
          backend:
            service:
              name: "{{ .Values.name }}"
              port:
                number: {{ .Values.submission_filemanager.port }}
